# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Mod
mod_id=brazier
mod_name=Brazier
mod_version=0.0.0-dev
mod_author=possible_triangle
release_type=release

# Common
mc_version=1.21.1
parchment_mappings_version=2024.11.17

# NeoForge
neoforge_version=21.1.252

# Fabric
fabric_api_version=0.116.9+1.21.1
fabric_loader_version=0.19.5

# Hosts
repository=teamgalena/brazier
maven_group=dev.galena
curseforge_project_id=402616
modrinth_project_id=5okEW6TG
version_strategy=with_minecraft_version