name = "Brazier Fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b61487890c3d604fd5243374af6e23b1b820f8352d47d9c7ca1ee87ea113b2ec"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
