[versions]
multikulti = "2.0.5"
config-api-port = "21.1.3"
jei = "19.27.0.340"
galena-hats = "1.3.1"

[libraries]
registrate-neoforge = { module = "com.tterrag.registrate:Registrate", version = "MC1.21-1.3.0+67" }
registrate-fabric = { module = "com.tterrag.registrate_fabric:Registrate", version = "1.3.6-MC1.21.1" }

multikulti-core-common = { group = "com.possible-triangle", name = "multikulti-1.21.1-core-common", version.ref = "multikulti" }
multikulti-registrate-common = { group = "com.possible-triangle", name = "multikulti-1.21.1-registrate-common", version.ref = "multikulti" }
multikulti-core-neoforge = { group = "com.possible-triangle", name = "multikulti-1.21.1-core-neoforge", version.ref = "multikulti" }
multikulti-registrate-neoforge = { group = "com.possible-triangle", name = "multikulti-1.21.1-registrate-neoforge", version.ref = "multikulti" }
multikulti-core-fabric = { group = "com.possible-triangle", name = "multikulti-1.21.1-core-fabric", version.ref = "multikulti" }
multikulti-registrate-fabric = { group = "com.possible-triangle", name = "multikulti-1.21.1-registrate-fabric", version.ref = "multikulti" }
multikulti-datagen-neoforge = { group = "com.possible-triangle", name = "multikulti-1.21.1-datagen-neoforge", version.ref = "multikulti" }

jei-common-api = { group = "mezz.jei", name = "jei-1.21.1-common-api", version.ref = "jei" }
jei-neoforge-api = { group = "mezz.jei", name = "jei-1.21.1-neoforge-api", version.ref = "jei" }
jei-neoforge = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jei" }
jei-fabric-api = { group = "mezz.jei", name = "jei-1.21.1-fabric-api", version.ref = "jei" }
jei-fabric = { group = "mezz.jei", name = "jei-1.21.1-fabric", version.ref = "jei" }
jei-lib = { group = "mezz.jei", name = "jei-1.21.1-lib", version.ref = "jei" }

config-api-port-fabric = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-fabric", version.ref = "config-api-port" }
config-api-port-common = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi", version.ref = "config-api-port" }

galena-hats-neoforge = { module = "dev.galena:hats-1.21.1-neoforge", version.ref = "galena-hats" }
galena-hats-fabric = { module = "dev.galena:hats-1.21.1-fabric", version.ref = "galena-hats" }

ponder = { group = "net.createmod.ponder", name = "ponder-neoforge", version = "1.0.82+mc1.21.1" }
flywheel = { group = "dev.engine-room.flywheel", name = "flywheel-neoforge-1.21.1", version = "1.0.6" }
