# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.123</version>
#    <timestamp>2026-09-28T15:37:57.778Z</timestamp>
#    <hash>9d521ee415ea61ee</hash>
# </meta>

blank_issues_enabled: false
