name = "Brazier NeoForge"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0863cca336283f8d13b2fb13afa47a9c53d90228dd1aadc48a7962e78cfed0f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
